name: Test Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Shallow clones should be disabled for better SonarCloud analysis
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: json
        coverage: pcov
        tools: composer:v2
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Run tests with coverage
      run: composer test:coverage
      
    - name: Fix coverage report paths for SonarCloud
      run: |
        mkdir -p reports/coverage
        # Ensure the coverage.xml file exists before copying
        if [ -f "reports/coverage.xml" ]; then
          cp -r reports/coverage.xml reports/coverage/
        else
          echo "Warning: reports/coverage.xml file not found"
          ls -la reports/
        fi
        
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=ranierif_api-mocker
          -Dsonar.organization=ranierif
          -Dsonar.php.coverage.reportPaths=reports/coverage.xml
          -Dsonar.sources=src
          -Dsonar.tests=tests
